POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###API-2
GET http://localhost:3000/states/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjgwMTc4ODY1fQ.tQk0ScfSewz7DwzbqCnw1zgFsS86DGv7OTFJShLAtM0

### API-3
GET http://localhost:3000/states/5/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjgwMTc4ODY1fQ.tQk0ScfSewz7DwzbqCnw1zgFsS86DGv7OTFJShLAtM0
### API-4
Post http://localhost:3000/districts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjgwMTc4ODY1fQ.tQk0ScfSewz7DwzbqCnw1zgFsS86DGv7OTFJShLAtM0
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}
### API-5
GET http://localhost:3000/districts/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjgwMTc4ODY1fQ.tQk0ScfSewz7DwzbqCnw1zgFsS86DGv7OTFJShLAtM0
### API-6
DELETE http://localhost:3000/districts/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjgwMTc4ODY1fQ.tQk0ScfSewz7DwzbqCnw1zgFsS86DGv7OTFJShLAtM0
###API-7
DELETE http://localhost:3000/districts/9/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjgwMTc4ODY1fQ.tQk0ScfSewz7DwzbqCnw1zgFsS86DGv7OTFJShLAtM0
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}
###API-8
GET http://localhost:3000/states/1/stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjgwMTc4ODY1fQ.tQk0ScfSewz7DwzbqCnw1zgFsS86DGv7OTFJShLAtM0
Content-Type: application/json

{
  "totalCases": 724355,
  "totalCured": 615324,
  "totalActive": 99254,
  "totalDeaths": 9777
}